# SPDX-License-Identifier: MIT
---
# Modules
nginx_cache_vts_module: true

# Trust proxy headers from wireguard network
nginx_cache_trusted_proxies: fd1e:39e:c6a4:1ee7::/64

# Per-tenant vhost setup
nginx_cache_tenants:
  - name: blitz_dev
    domain: cache.dev.coursepoursuite.fr
    backend_host: srv.dev.coursepoursuite.fr
    tls_cert_path: /var/lib/lego/certificates/blitz_dev.crt
    tls_key_path: /var/lib/lego/certificates/blitz_dev.key

  # - name: "tenant_beta"
  #   domain: "cache2.example.com"
  #   backend_host: "10.0.0.11"
  #   # Inherits default backend_port (30120), max_size (10g), keys_zone_size (10m)
  #   tls_cert_path: "/etc/ssl/certs/tenant_beta.crt"
  #   tls_key_path: "/etc/ssl/private/tenant_beta.key"

# Honeypot configuration
fail2ban_honeypot_logpath: /var/log/nginx/cache.dev.coursepoursuite.fr.access.log
