# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: ens3
    mac: fa:16:3e:bf:90:b5
    dhcp4: true
    ipv6_address: "2001:41d0:305:2100::1:7390/128"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "2001:41d0:305:2100::1"
        onlink: true

wireguard_address: fd1e:39e:c6a4:face::7390
wireguard_public_key: l/XIYLDGOHnM6Agj+aYxeng0rTuzR2Rp4TlHQy09dX4=
