# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Configure base system and networking
    options:
      common_timezone:
        type: str
        default: Etc/UTC
        description: System timezone (e.g., Europe/Paris, Etc/UTC).
      common_upgrades_email:
        type: str
        description: Email address to receive unattended-upgrades reports.
      common_sudoers_email:
        type: str
        description: Email address to receive sudoers security reports.
