# SPDX-License-Identifier: MIT
---
- name: Install nginx and required tools
  ansible.builtin.apt:
    name:
      - nginx
      - ssl-cert
      - curl
    state: present

- name: Install and setup VTS module
  ansible.builtin.import_tasks: vts-module.yml
  when: nginx_cache_vts_module

- name: Deploy nginx configuration
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload nginx

- name: Disable default vhost
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy default catch-all vhost for https traffic
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default.conf
    mode: "0644"
  notify: Reload nginx

- name: Enable default catch-all vhosts
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default.conf
    dest: /etc/nginx/sites-enabled/default.conf
    state: link
  notify: Restart nginx

- name: Certificates deployment setup
  ansible.builtin.import_tasks: cert-deploy.yml

- name: Cache vhosts setup
  ansible.builtin.import_tasks: cache-setup.yml

# - name: Deploy nginx logging config
#   ansible.builtin.template:
#     src: logging.conf.j2
#     dest: /etc/nginx/conf.d/logging.conf
#     mode: "0644"
#   notify: Reload nginx

- name: Deploy alloy config
  ansible.builtin.template:
    src: 50-nginx.alloy.j2
    dest: /etc/alloy.d/50-nginx.alloy
    mode: "0644"
  notify: Reload alloy

- name: Deploy firewall rule
  ansible.builtin.copy:
    content: |
      tcp dport { 80, 443 } accept \
      comment "Accept https traffic"
    dest: /etc/nftables.d/filter-input/nginx-cache.nft
    mode: "0644"
  notify: Reload nftables

- name: Deploy firewall rule for acme and cert-sync
  ansible.builtin.copy:
    content: |
      tcp dport { 80, 8443 } accept \
      comment "Accept https traffic for acme and cert-sync"
    dest: /etc/nftables.d/filter-input-wg/nginx-acme.nft
    mode: "0644"
  when: inventory_hostname == groups['caches'][0]
  notify: Reload nftables
