# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Deploy Incus server
    options:
      incus_net_routed_enabled:
        type: bool
        default: false
        description: Enable the possibility to create routed interface config.
      incus_config_core:
        type: dict
        default: {}
        description: Core daemon configuration
      incus_config_acme:
        type: dict
        default: {}
        description: ACME configuration
