# SPDX-License-Identifier: MIT
---
- name: Restart ssh
  ansible.builtin.systemd_service:
    name: ssh.service
    state: restarted

- name: Reload ssh
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded

- name: Reload nftables
  ansible.builtin.systemd_service:
    name: nftables.service
    state: reloaded
