# SPDX-License-Identifier: MIT
---
cfx_server_connect_endpoint: connect.staging.blitz-infra.net
cfx_server_txadmin_endpoint: txadmin.staging.blitz-infra.net

cfx_server_build_number: 25770
cfx_server_account: Sylou:188175

# cfx_server_cpu_affinity: "0,1"
