# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: eth0
    dhcp4: true
    ipv6_address: "2a01:4f8:c014:5d45::1/64"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "fe80::1"

wireguard_int_address: fd1e:39e:c6a4:1ee7::5d45
# wireguard_int_public_key: GQ2pfRtPa0zb7tE6c2LNMUUmkC3ww1j0y2SQBYP6LW8=
