# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: eth0
    dhcp4: true
    ipv6_address: "2a01:4f8:c014:1291::1/64"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "fe80::1"

nftables_enable_forwarding: true

wireguard_int_address: fd1e:39e:c6a4:1ee7::1291
wireguard_int_public_key: B/1IsQXUdV4HRpVPVuXqAYd9TXVAYUPMK89/X6/6qiI=

wireguard_ops_address: fd1e:39e:c6a4:42::1291
wireguard_ops_peers: "{{ vault_wireguard_ops_peers }}"
