# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: ens3
    mac: fa:16:3e:04:9f:6c
    dhcp4: true
    ipv6_address: "2001:41d0:20a:900::64f/128"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "2001:41d0:20a:900::"
        onlink: true

nftables_enable_forwarding: true

wireguard_int_address: fd1e:039e:c6a4:1ee7::64f
wireguard_int_public_key: B/1IsQXUdV4HRpVPVuXqAYd9TXVAYUPMK89/X6/6qiI=

wireguard_ops_address: fd1e:039e:c6a4:42::64f
wireguard_ops_peers: "{{ vault_wireguard_ops_peers }}"
