# SPDX-License-Identifier: MIT
---
slapd_enable_tls: false
slapd_config_passwd: "{{ vault_slapd_config_passwd }}"

slapd_databases:
  - base_dn: "{{ base_dn }}"
    db_path: /var/lib/ldap/blitz-infra
    admin_passwd: "{{ vault_slapd_admin_infra_pass }}"
  - base_dn: dc=blitz-fivem,dc=fr
    db_path: /var/lib/ldap/blitz-fivem
    admin_passwd: "{{ vault_slapd_admin_fivem_pass }}"
