# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Deploy and configure Prometheus Alertmanager
    options:
      alertmanager_listen_address:
        type: str
        default: "[::]:9093"
        description: IP and port for the HTTP server to listen on.

      alertmanager_config:
        type: dict
        required: true
        description: The full YAML configuration structure for Alertmanager routes and receivers.
