# SPDX-License-Identifier: MIT
---
# Global variables
domain: staging.blitz-infra.net
base_dn: dc=staging,dc=blitz-infra,dc=net

# Email reports
common_upgrades_email: "root@{{ domain }}"
fail2ban_destemail: "security@{{ domain }}"

# Monitoring
alloy_loki_endpoint: monitoring.staging.blitz-infra.net
alloy_prometheus_endpoint: monitoring.staging.blitz-infra.net

# SSH
sshd_global_config:
  AddressFamily: any
  PermitRootLogin: prohibit-password
  PasswordAuthentication: "yes"
  AllowTcpForwarding: "yes"

sshd_firewall_chain: "filter-input"
