# SPDX-License-Identifier: MIT
---
# ACME
vault_lego_ovh_app_key: 4598c5bacf07e4bf
vault_lego_ovh_app_secret: 0db2c4e524e16b65a8573eb2ae3793d2
vault_lego_ovh_consumer_key: 06f8955b8145b270feac499e0a002cb2

# SSSD
vault_sssd_bind_passwd: n4OyERlcb0OEneG3paHxSHQT
