{
 "title": "Nginx VTS Stats (Kubernetes)",
 "description": "Show stats from nginx VTS module (direct, without exporter)",
 "tags": [
  "prometheus",
  "nginx",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_vts_info, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nginx_vts_info{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "host",
    "label": "HTTP Host",
    "query": "label_values(nginx_vts_server_requests_total{namespace=\"$namespace\", host!=\"*\"}, host)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nginx_vts_server_requests_total{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Cache events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_cache_total[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests by host",
   "type": "timeseries",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total[5m]) > 0) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Cache throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_cache_bytes_total[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(nginx_vts_cache_usage_bytes{cache_size=\"max\"})",
     "legendFormat": "max"
    },
    {
     "expr": "nginx_vts_cache_usage_bytes{cache_size=\"used\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_main_connections{status=~\"active|writing|reading|waiting\"}[10m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Upstream throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_bytes_total[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(nginx_vts_server_request_seconds > 0)",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(nginx_vts_upstream_response_seconds > 0) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Shared memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nginx_vts_main_shm_usage_bytes) by (shared)",
     "legendFormat": "{{ shared }}"
    }
   ]
  },
  {
   "title": "Upstream requests",
   "type": "timeseries",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_requests_total{code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  }
 ]
}