{
 "title": "Prometheus server",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself. Designed primarily for Prometheus 2.7.x.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Prometheus",
    "label": "prometheus instance (hover for info)",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   },
   {
    "name": "RuleGroup",
    "query": {
     "query": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",instance=~\"$Prometheus\"}"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "name",
    "query": {
     "query": "label_values(prometheus_build_info{instance=\"${Prometheus}\"}, prometheus)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basics (instance ${name})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "{{version}} - {{revision}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Age"
    }
   ]
  },
  { "title": "Ingestion (instance ${name})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Head Time series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Time series"
    }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Head Appenders"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "samples/s"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Removed"
    }
   ]
  },
  { "title": "Compaction (instance ${name})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Head Time Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Min"
    },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    {
     "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Head GC Time/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "GC Time/s"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Blocks Loaded"
    }
   ]
  },
  {
   "title": "TSDB Reloads/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Reloads"
    }
   ]
  },
  {
   "title": "WAL Fsync&Truncate Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Fsync Latency"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m]) / rate(prometheus_tsdb_wal_trunacte_duration_seconds_count{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Truncate Latency"
    }
   ]
  },
  {
   "title": "TSDB Problems/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "WAL Corruptions"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Reload Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Head Series Not Found"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Compaction Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Retention Cutoff Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_checkpoint_creations_failed_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "WAL Checkpoint Creation Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_checkpoint_deletions_failed_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "WAL Checkpoint Deletion Failures"
    }
   ]
  },
  {
   "title": "Compactions/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "Compaction Time/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])"
    }
   ]
  },
  {
   "title": "Retention Cutoffs/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_time_retentions_total[10m])",
     "legendFormat": "Time Cutoffs"
    },
    {
     "expr": "rate(prometheus_tsdb_size_retentions_total[10m])",
     "legendFormat": "Size Cutoffs"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Time Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_range_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_seconds_count{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Chunk Time Range"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Bytes/Sample",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Bytes/Sample"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"prometheus\",instance=~\"$Prometheus\"}[10m])",
     "legendFormat": "Chunk Samples"
    }
   ]
  },
  {
   "title": "Resource Usage  (instance ${name})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "5m rate"
    }
   ]
  },
  {
   "title": "Symbol Tables Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "prometheus_tsdb_symbol_table_size_bytes{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes_total{job=\"prometheus\",instance=~\"$Prometheus\"} or prometheus_tsdb_storage_blocks_bytes{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "process_max_fds{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"prometheus\",instance=~\"$Prometheus\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "HTTP Server  (instance ${name})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "HTTP requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Query Engine  (instance ${name})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }
  },
  {
   "title": "Query engine timings/s",
   "type": "timeseries",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule group evaulation problems/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])  ",
     "legendFormat": "Rule group missed"
    },
    {
     "expr": "rate(prometheus_rule_evaluation_failures_total{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Rule evals failed"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum{job=\"prometheus\",instance=~\"$Prometheus\"}[5m])",
     "legendFormat": "Rule evaluation duration"
    }
   ]
  },
  { "title": "Rule Group: $RuleGroup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 }, "repeat": "RuleGroup" },
  {
   "title": "$RuleGroup: Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "prometheus_rule_group_interval_seconds{job=\"prometheus\",instance=~\"$Prometheus\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "Interval"
    },
    {
     "expr": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",instance=~\"$Prometheus\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "Last Duration"
    }
   ]
  },
  {
   "title": "$RuleGroup: Rules",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "prometheus_rule_group_rules{job=\"prometheus\",instance=~\"$Prometheus\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "Rules"
    }
   ]
  }
 ]
}