# SPDX-License-Identifier: MIT
---
mariadb_bind_address: "*"
mariadb_env: production
mariadb_hide_passwords: true

mariadb_databases:
  - name: fivem
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    state: present

mariadb_users:
  - name: fivem
    host: localhost
    password: "{{ vault_fivem_db_pass }}"
    priv: fivem.*:ALL

mariadb_pam_enable: true
mariadb_pam_users: "{{ vault_mariadb_pam_users }}"
