# SPDX-License-Identifier: MIT
---
- name: Install restic and rclone
  ansible.builtin.apt:
    name:
      - restic
      - rclone
    state: present

- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ restic_group }}"
    system: true
    state: present

- name: Create restic system user
  ansible.builtin.user:
    name: "{{ restic_user }}"
    group: "{{ restic_group }}"
    system: true
    home: "{{ restic_home }}"
    shell: /usr/sbin/nologin
    state: present

- name: Create specialized directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: '0700'
  loop:
    - "{{ restic_dump_dir }}"
    - "{{ restic_cache_dir }}"

- name: Setup mariadb requirements
  ansible.builtin.import_tasks: mariadb.yml
  when: restic_mariadb_backup

- name: Setup OpenLDAP requirements
  ansible.builtin.import_tasks: openldap.yml
  when: restic_openldap_backup

- name: Create Rclone config directory
  ansible.builtin.file:
    path: "{{ restic_home }}/.config/rclone"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: '0700'

- name: Obscure the FTP password using rclone on the remote server
  ansible.builtin.command: "rclone obscure {{ restic_ovh_ftp_pass }}"
  register: restic_obscured_password
  changed_when: false

- name: Configure Rclone for OVH FTP
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ restic_home }}/.config/rclone/rclone.conf"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: '0600'

- name: Deploy exclude file
  ansible.builtin.template:
    src: excludes.txt.j2
    dest: "{{ restic_home }}/excludes.txt"
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: '0640'

- name: Deploy backup scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/usr/local/sbin/{{ item }}"
    owner: root
    group: "{{ restic_group }}"
    mode: '0750'
  loop:
    - backup.sh
    - backup-check.sh

- name: Install systemd services for backup
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - restic.service
    - restic-check.service
    # - restic-off-site.service
  notify: Reload systemd

- name: Check if Restic repository is already initialized
  ansible.builtin.command: restic snapshots
  register: restic_check
  failed_when: false
  changed_when: false
  environment:
    RESTIC_CACHE_DIR: "{{ restic_cache_dir }}"
    RESTIC_REPOSITORY: "{{ restic_repo_path }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
    RCLONE_CONFIG: "{{ restic_home }}/.config/rclone/rclone.conf"

- name: Initialize Restic backup repository
  ansible.builtin.command: restic init
  when: restic_check.rc != 0
  changed_when: true
  environment:
    RESTIC_CACHE_DIR: "{{ restic_cache_dir }}"
    RESTIC_REPOSITORY: "{{ restic_repo_path }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
    RCLONE_CONFIG: "{{ restic_home }}/.config/rclone/rclone.conf"

- name: Ensure Restic cache directory is owned by the restic user
  ansible.builtin.file:
    path: "{{ restic_cache_dir }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    recurse: true

- name: Install systemd timers
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - restic.timer
    - restic-check.timer
  notify: Reload systemd

- name: Activate systemd timers
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - restic.timer
    - restic-check.timer
