# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: ens3
    mac: fa:16:3e:04:9f:6c
    dhcp4: true
    ipv6_address: "2001:41d0:20a:900::64f/128"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "2001:41d0:20a:900::"
        onlink: true

wireguard_int_address: fd1e:39e:c6a4:face::64f
wireguard_int_public_key: Mld4kDQ+em6BP740MtwcNK0iVymj4QNUvZb+E7qb3S0=

nftables_enable_forwarding: true
wireguard_ops_address: fd1e:39e:c6a4:cafe::64f
wireguard_ops_peers: "{{ vault_wireguard_ops_peers }}"
