# SPDX-License-Identifier: MIT
---
# Core System Defaults
lego_arch: "linux_amd64"
lego_user: lego
lego_group: lego
lego_home: /var/lib/lego
lego_config_dir: /etc/lego
lego_webroot: /var/www/html

lego_accounts: {}
lego_challenges: {}
lego_hooks:
  deploy:
    command: /usr/local/sbin/lego-deploy-hook.sh
lego_deploy_targets: []
