# SPDX-License-Identifier: MIT
---
# Directories
cfx_server_home_dir: /srv/cfx
cfx_server_install_dir: /opt/cfx
cfx_server_data_dir: "{{ cfx_server_home_dir }}/txData"

# Service user
cfx_server_user: citizenfx
cfx_server_group: citizenfx
cfx_server_sftp_keys: "{{ vault_cfx_server_sftp_keys }}"

# Database
cfx_server_db_name: fivem
cfx_server_db_user: fivem
cfx_server_db_pass: "{{ vault_fivem_db_pass }}"

# Provider
cfx_server_provider_name: Blitz Staging
cfx_server_provider_logo: https://github.com/citizenfx/txAdmin/raw/master/docs/banner.png
