# SPDX-License-Identifier: MIT
---
- name: Reload daemon and restart cfx-server
  ansible.builtin.systemd_service:
    name: cfx-server.service
    state: restarted
    daemon_reload: true

- name: Restart cfx-server
  ansible.builtin.systemd_service:
    name: cfx-server.service
    state: restarted

- name: Reload alloy
  ansible.builtin.uri:
    url: "http://[::1]:12345/-/reload"
    method: POST
    status_code: 200

- name: Reload nftables
  ansible.builtin.systemd_service:
    name: nftables.service
    state: reloaded
