---
games:
  hosts:
    game.staging.blitz-infra.net:
caches:
  hosts:
    cache.staging.blitz-infra.net:
mta_gateway:
  hosts:
    manager.staging.blitz-infra.net:
directory:
  hosts:
    manager.staging.blitz-infra.net:
monitor:
  hosts:
    manager.staging.blitz-infra.net:
