---
ungrouped:
  hosts:
    manager.staging.blitz-infra.net:
      ansible_host: 2a01:4f8:c014:1291::1
games:
  hosts:
    game.staging.blitz-infra.net:
      ansible_host: 2a01:4f8:c014:5d45::1
caches:
  hosts:
    cache.staging.blitz-infra.net:
      ansible_host: 2a01:4f8:c014:49ad::1
