# SPDX-License-Identifier: MIT
---
- name: Install Alertmanager package
  ansible.builtin.apt:
    name: prometheus-alertmanager
    state: present

- name: Deploy Alertmanager environment defaults
  ansible.builtin.template:
    src: alertmanager.env.j2
    dest: /etc/default/prometheus-alertmanager
    mode: "0644"
  notify: Restart alertmanager

- name: Deploy Alertmanager main configuration
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    # owner: root
    # group: prometheus
    # mode: "0640"
    mode: "0644"
  notify: Reload alertmanager

# - name: Deploy nftables firewall rule for Alertmanager
#   ansible.builtin.copy:
#     content: |
#       tcp dport 9093 accept \
#       comment "Accept alertmanager access"
#     dest: /etc/nftables.d/filter-input-wg/alertmanager.nft
#     mode: "0644"
#   notify: Reload nftables
