# SPDX-License-Identifier: MIT
---
- name: Ensure root uses unix_socket authentication
  ansible.mysql.mysql_user:
    name: root
    host: localhost
    plugin: unix_socket

- name: Ensure that anonymous users are absent
  ansible.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent

- name: Ensure that the test database is absent
  ansible.mysql.mysql_db:
    name: test
    state: absent

- name: Get all existing hosts for the root user
  ansible.mysql.mysql_query:
    query: SELECT Host FROM mysql.user WHERE User = 'root'
  register: mariadb_root_hosts
  check_mode: false

- name: Ensure root can only login from localhost (Drop all unknown hosts)
  ansible.mysql.mysql_user:
    name: root
    host: "{{ item.Host }}"
    state: absent
  loop: "{{ mariadb_root_hosts.query_result[0] }}"
  when: item.Host not in ['localhost', '127.0.0.1', '::1']
