# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Deploy and manage Cfx Server
    options:
      # Required Endpoints/Build
      cfx_server_connect_endpoint:
        type: str
        required: true
        description: The public endpoint for player connection (e.g., play.example.com)
      cfx_server_txadmin_endpoint:
        type: str
        required: true
        description: The public endpoint for txAdmin (e.g., txadmin.example.com)
      cfx_server_build_number:
        type: str
        required: true
        description: The specific Cfx Server build number to install (e.g., "7290")

      # Installation Configuration
      cfx_server_install_dir:
        type: str
        default: /opt/cfx
        description: Artifacts installation directory
      cfx_server_data_dir:
        type: str
        default: "{{ cfx_server_home_dir }}/txData"
        description: The path to the txData folder, which contains the txAdmin logs, configs, and data

      # Database Configuration
      cfx_server_db_host:
        type: str
        default: localhost
      cfx_server_db_port:
        type: int
        default: 3306
      cfx_server_db_name:
        type: str
        default: cfx_server
      cfx_server_db_user:
        type: str
        default: cfx
      cfx_server_db_pass:
        type: str
        required: true
        no_log: true

      # Service / User Configuration
      cfx_server_user:
        type: str
        default: cfx
      cfx_server_group:
        type: str
        default: cfx
      cfx_server_home_dir:
        type: str
        default: /var/opt/cfx
      cfx_server_sftp_keys:
        type: list
        elements: str
        default: []
        description: List of SSH public keys for SFTP access
      cfx_server_cpu_affinity:
        type: str
        description: List of CPU cores that the process is running on (e.g., "0,1,2,3")

      # Meta Information
      cfx_server_provider_name:
        type: str
        default: "DefaultHosting"
      cfx_server_provider_logo:
        type: str
        description: URL to the provider banner/logo
      cfx_server_account:
        type: str
        description: txAdmin initial account
