# SPDX-License-Identifier: MIT
---
# Service user
fxserver_user: citizenfx
fxserver_group: citizenfx
fxserver_sftp_keys: "{{ vault_fxserver_sftp_keys }}"

# Database
fxserver_db_name: fivem
fxserver_db_user: fivem
fxserver_db_pass: "{{ vault_fivem_db_pass }}"

# Provider
fxserver_provider_name: Blitz Infra
fxserver_provider_logo: https://dunb17ur4ymx4.cloudfront.net/webstore/logos/4f9a20e4fbc53a4b0463a5a35fda749a34caa0c7.png
