# SPDX-License-Identifier: MIT
---
wireguard_port: 51820
# wireguard_enable_forwarding: false

# # Operators network
# wireguard_ops_nic: wg1
# wireguard_ops_port: 51821
# # Defaulting to an empty list prevents undefined variable errors in loops
# wireguard_ops_peers: []
