# SPDX-License-Identifier: MIT
---
# Global sshd configuration
sshd_global_config: {}

# Default match blocks
sshd_match_blocks: []

# Configurable firewall chain folder (e.g., 'filter-input-v6' or 'filter-input')
sshd_firewall_chain: "filter-input-v6"
