# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Deploy WireGuard VPNs using systemd-networkd
    options:
      wireguard_port:
        type: int
        default: 51820
        description: Listen port for the internal network.
      wireguard_address:
        type: str
        required: true
        description: IPv6 address for the internal interface.
      wireguard_public_ipv6:
        type: str
        required: true
        description: IPv6 address for the vpn perring.
      wireguard_public_key:
        type: str
        description: The public key of the internal peer/server.
