# SPDX-License-Identifier: MIT
---
# Endpoints
fxserver_connect_endpoint: connect.dev.coursepoursuite.fr
fxserver_txadmin_endpoint: txadmin.dev.coursepoursuite.fr

# Build
fxserver_build_number: 35245

# Service user
fxserver_user: citizenfx
fxserver_group: citizenfx
fxserver_sftp_keys: "{{ vault_fxserver_sftp_keys }}"

# Database
fxserver_db_name: fivem
fxserver_db_user: fivem
fxserver_db_pass: "{{ vault_fivem_db_pass }}"

# txAdmin
fxserver_account: Carbonaraaaaa:16402109
