# SPDX-License-Identifier: MIT
---
sshd_global_config:
  AddressFamily: any

sshd_match_blocks:
  - condition: "User {{ fxserver_user }}"
    rules:
      # ChrootDirectory: "%h"
      # ForceCommand: "internal-sftp -u 0022 -l VERBOSE"
      AllowAgentForwarding: "no"
      AllowStreamLocalForwarding: "yes"
      AllowTcpForwarding: "yes"
      X11Forwarding: "no"
      PermitTTY: "yes"
