# SPDX-License-Identifier: MIT
---
# Email
vault_postfix_relay_auth_password: JvPYbbhI9nJDuKlzI4wj57wA

# FXServer
vault_fxserver_sftp_keys:
  - ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBI+NivrKg4cHbbxWWafmwWrgp6O2rmoT5xTDoM9VvSx6NFqQqp79gOpUI7ZFmyBSC4+qfVasun/1U7Xrk/vdg+cthRUlFeZTNzd2z1j6p2u4hNNUGdksqqRtambu8zgxgw== ecdsa-key-20260530
  - ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBKIq4mL5xScIDsvWaVQvNzZqgVme1mFd8ykQjy2SVmqKHYmBATXMFguYWiEnqyYwa/EbPPBhOL1gVeCUL0OFb8rPToLj2e9uzvKPJk91Uwuw6aRe+ENuHuBpVnOYwaiHAA== ecdsa-key-20260912

# Database
vault_fivem_db_pass: vcGXUYUzs2jEV7lvJFTMvk9y

vault_mariadb_pam_users:
  - name: sylou
    host: fd1e:39e:c6a4:cafe::99
    priv: "*.*:SELECT"
    state: present
  - name: carbon
    host: fd1e:39e:c6a4:cafe::100
    priv: "fivem.*:ALL"
    state: present
