# SPDX-License-Identifier: MIT
---
- name: Restart alertmanager
  ansible.builtin.systemd_service:
    name: prometheus-alertmanager.service
    state: restarted

- name: Reload alertmanager
  ansible.builtin.systemd_service:
    name: prometheus-alertmanager.service
    state: reloaded

# - name: Reload nftables
#   ansible.builtin.systemd_service:
#     name: nftables.service
#     state: reloaded
