# SPDX-License-Identifier: MIT
---
- name: Install common packages
  ansible.builtin.apt:
    name:
      - bash-completion
      - dnsutils
      - htop
      - iproute2
      - logrotate
      - mtr-tiny
      - tpm2-tools # used by systemd credentials
      - unattended-upgrades
      - vim
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install the kexec-tools package if we're running on a physical server
  ansible.builtin.apt:
    name: kexec-tools
    state: present
  when: ansible_facts['virtualization_role'] | default('') == 'host'

- name: Remove cloud-init
  ansible.builtin.apt:
    name: cloud-init
    state: absent
    purge: true
    autoremove: true

- name: Set hostname from inventory_hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
    use: debian

- name: Configure hosts file from inventory_hostname
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"

- name: Set timezone via localtime
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Ensure systemd-resolved is installed
  ansible.builtin.apt:
    name: systemd-resolved
    state: present

- name: Disable unused defaults in systemd-resolved
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?{{ item.key }}\b'
    line: "{{ item.key }}={{ item.value }}"
    firstmatch: true
    state: present
  loop:
    - { key: LLMNR, value: "false" }
  notify: Reload systemd-resolved

- name: Define report mail for unattended-upgrades
  ansible.builtin.lineinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^\s*(//\s*)?Unattended-Upgrade::Mail\b'
    line: 'Unattended-Upgrade::Mail "{{ common_upgrades_email }}";'
  when: common_upgrades_email is defined
  notify: Restart unattended-upgrades

- name: Define report email for sudoers alerts
  ansible.builtin.copy:
    dest: /etc/sudoers.d/mail-report
    content: |
      Defaults	mailto="{{ common_sudoers_email }}"
    mode: "0440"
  when: common_sudoers_email is defined
