---
games:
  hosts:
    game.blitz-infra.net:
caches:
  hosts:
    cache1.blitz-infra.net:
    cache2.blitz-infra.net:
mta_gateway:
  hosts:
    manager.blitz-infra.net:
directory:
  hosts:
    manager.blitz-infra.net:
monitor:
  hosts:
    manager.blitz-infra.net:
