---
ungrouped:
  hosts:
    manager.blitz-infra.net:
      # ansible_host: fd1e:39e:c6a4:face::64f
caches:
  hosts:
    cache1.blitz-infra.net:
      # ansible_host: fd1e:39e:c6a4:face::614
    cache2.blitz-infra.net:
      # ansible_host: fd1e:39e:c6a4:face::629
games:
  hosts:
    game1.blitz-infra.net:
      # ansible_host: fd1e:39e:c6a4:face::67
    sandbox1.blitz-infra.net:
sandboxes:
  hosts:
    sandbox1.blitz-infra.net:
      # ansible_user: debian
      ansible_host: 2001:41d0:801:2000::74f2
