# SPDX-License-Identifier: MIT
---
# Email
postfix_relayhost: smtp.blitz-infra.net

# FXServer
fxserver_provider_name: Blitz Infra
fxserver_provider_logo: https://dunb17ur4ymx4.cloudfront.net/webstore/logos/4f9a20e4fbc53a4b0463a5a35fda749a34caa0c7.png
