# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: ens3
    mac: fa:16:3e:03:f0:35
    dhcp4: true
    ipv6_address: "2001:41d0:305:2100::1:738f/128"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "2001:41d0:305:2100::1"
        onlink: true

wireguard_address: fd1e:39e:c6a4:face::738f
wireguard_public_key: Zl72auvXK4Lb+5IYPPqUbT00zeDeRzCf/E4aU6C3eC0=
