# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: ens3
    mac: fa:16:3e:b4:78:d5
    dhcp4: true
    ipv6_address: "2001:41d0:20a:900::629/128"
    dns: "{{ dns_servers }}"
    ntp: "{{ ntp_servers }}"
    domains: ["{{ domain }}"]
    routes:
      - dest: "::/0"
        gw: "2001:41d0:20a:900::"
        onlink: true

  # - name: enp8s0f0np0
  #   mac: 34:5a:60:03:7c:6a
  #   dhcp4: true
  #   ipv6_address: "2001:41d0:20f:9200::/56"
  #   dns: "{{ dns_servers }}"
  #   ntp: "{{ ntp_servers }}"
  #   domains: "{{ domains }}"
  #   routes:
  #     - dest: "::/0"
  #       gw: "fe80::1"
  #       onlink: true

wireguard_int_address: fd1e:039e:c6a4:face::629
wireguard_int_public_key: GQ2pfRtPa0zb7tE6c2LNMUUmkC3ww1j0y2SQBYP6LW8=
