# SPDX-License-Identifier: MIT
---
lego_version: "5.5.1"

lego_accounts:
  blitz-security:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "security@{{ domain }}"
    keyType: EC384
    acceptsTermsOfService: true
