# SPDX-License-Identifier: MIT
---
# Global network variables
net_internal_base: "fd1e:39e:c6a4:face::"
net_internal_mask: 64
net_operators_base: "fd1e:39e:c6a4:cafe::"
net_operators_mask: 64

## OVH network
dns_servers:
  - 213.186.33.99
  - 2001:41d0:3:163::1
ntp_servers:
  - ntp0.ovh.net

# Wireguard
wireguard_int_network: "{{ net_internal_base }}/{{ net_internal_mask }}"
wireguard_ops_network: "{{ net_operators_base }}/{{ net_operators_mask }}"
