# SPDX-License-Identifier: MIT
---
# Global variables
domain: blitz-infra.net
base_dn: dc=blitz-infra,dc=net
# install_mail_catcher: false

# Common
common_timezone: Europe/Paris
common_upgrades_email: "root@{{ domain }}"

# Backup
restic_admin_email: "root@{{ domain }}"

# Monitoring
alloy_loki_endpoint: monitoring.blitz-infra.net
alloy_prometheus_endpoint: monitoring.blitz-infra.net
