# SPDX-License-Identifier: MIT
---
- name: Restart prometheus
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: restarted

- name: Reload prometheus
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: reloaded

- name: Reload alloy
  ansible.builtin.uri:
    url: "http://[::1]:12345/-/reload"
    method: POST
    status_code: 200

- name: Reload nftables
  ansible.builtin.systemd_service:
    name: nftables.service
    state: reloaded
