# SPDX-License-Identifier: MIT
---
- name: Setup cache server
  hosts: cache
  roles:
    - { role: common, tags: ["common"] }
    - { role: nftables, tags: ["nftables"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: alloy, tags: ["alloy", "monitoring"] }
    # - { role: prometheus_systemd_exporter, tags: ["monitoring"] }
    - { role: sssd, tags: ["sssd"] }
    - { role: sshd, tags: ["sshd"] }
    - { role: postfix, tags: ["postfix"] }
    # - os_hardening
    # - ssh_hardening
    - { role: lego, tags: ["lego"] }
    - { role: nginx_core, tags: ["nginx"] }
    # - nginx_hardening
    - { role: nginx_cache, tags: ["nginx", "cache"] }
    # - { role: fail2ban, tags: ["fail2ban"] }
    # - { role: crowdsec, tags: ["crowdsec"] }
