# SPDX-License-Identifier: MIT
---
- name: Setup container runtime
  hosts: game.*
  gather_facts: false
  roles:
    - role: incus
      tags: ["incus"]

- name: Setup user directory
  hosts: core.*
  roles:
    - role: slapd
      tags: ["slapd", "ldap"]

- name: Setup mailling infrastructure
  hosts: all
  roles:
    - role: postfix
      tags: ["postfix"]

- name: Setup caches
  hosts: caches
  roles:
    - role: nginx_cache
      tags: ["nginx", "cache"]

- name: Setup certificates via ACME
  hosts: caches, core.*
  roles:
    - role: lego
      tags: ["lego"]
