# SPDX-License-Identifier: MIT
---
- name: Setup certificates via ACME
  hosts: mta_gateway
  roles:
    - role: lego
      tags: ["lego"]

# - name: Deploy staging mail sandbox
#   hosts: mta_gateway
#   roles:
#     - role: mailpit
#       tags: ["mailpit"]
#       when: install_mail_catcher | bool

- name: Setup mailling infrastructure
  hosts: all
  roles:
    - role: postfix
      tags: ["postfix"]
