# SPDX-License-Identifier: MIT
---
- name: Setup manager
  hosts: manager.blitz-infra.net
  roles:
    - { role: common, tags: ["common"] }
    - { role: nftables, tags: ["nftables"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: alloy, tags: ["alloy", "monitoring"] }
    # - { role: prometheus_systemd_exporter, tags: ["monitoring"] }
    # - { role: prometheus_smartctl_exporter, tags: ["monitoring"] }
    # - { role: prometheus_ipmi_exporter, tags: ["monitoring"] }
    - { role: sssd, tags: ["sssd"] }
    - { role: sshd, tags: ["sshd"] }
    - { role: postfix, tags: ["postfix"] }
    - { role: slapd, tags: ["slapd", "ldap"] }
    # - os_hardening
    # - ssh_hardening
    - { role: lego, tags: ["lego"] }
    - { role: nginx_core, tags: ["nginx"] }
    - { role: prometheus, tags: ["prometheus"] }
    - { role: loki, tags: ["loki"] }
    # - { role: alertmanager, tags: ["alertmanager"] }
    - { role: grafana, tags: ["grafana"] }
    - { role: nginx_proxy, tags: ["nginx"] }
    # - { role: fail2ban, tags: ["fail2ban"] }
    # - { role: crowdsec, tags: ["crowdsec"] }
    # - { role: restic, tags: ["restic"] }
