# SPDX-License-Identifier: MIT
---
- name: Deploy monitoring agents
  hosts: all
  roles:
    - role: alloy
      tags: ["alloy"]

- name: Deploy monitoring backend
  hosts: core.*
  roles:
    - role: prometheus
      tags: ["prometheus"]
    - role: loki
      tags: ["loki"]
    - role: grafana
      tags: ["grafana"]
    # - role: alertmanager
    #   tags: ["alertmanager"]

- name: Setup reverse proxy
  hosts: core.*
  roles:
    - role: nginx_proxy
      tags: ["nginx", "proxy"]
