# SPDX-License-Identifier: MIT
---
- name: Setup web foundations
  hosts: monitor, caches, games
  roles:
    - role: nginx_core
      tags: ["nginx"]

- name: Setup reverse proxies
  hosts: monitor, games
  roles:
    - role: nginx_proxy
      tags: ["nginx", "proxy"]

- name: Setup cache configuration
  hosts: caches
  roles:
    - role: nginx_cache
      tags: ["nginx", "cache"]
