# SPDX-License-Identifier: MIT
---
- name: Setup web foundations
  hosts: caches, games, manager.blitz-infra.net, !sandboxes
  roles:
    - role: nginx_core
      tags: ["nginx"]

- name: Setup reverse proxies
  hosts: games, manager.blitz-infra.net, !sandboxes
  roles:
    - role: nginx_proxy
      tags: ["nginx", "proxy"]

- name: Setup cache configuration
  hosts: caches
  roles:
    - role: nginx_cache
      tags: ["nginx", "cache"]
