# SPDX-License-Identifier: MIT
---
- name: Load argon2 module
  community.general.ldap_attrs:
    dn: cn=module{0},cn=config
    attributes:
      olcModuleLoad: argon2
    state: present

- name: Define the default password hashing method
  community.general.ldap_attrs:
    dn: olcDatabase={-1}frontend,cn=config
    attributes:
      olcPasswordHash: '{ARGON2}'
    state: exact
