# SPDX-License-Identifier: MIT
---
- name: Install slapd and tools
  ansible.builtin.apt:
    name:
      - slapd
      - ldap-utils
      - schema2ldif
      - python3-ldap
      - libarchive-zip-perl  # required by add-rfc2307bis.sh script
    state: present

- name: Include schema tasks
  ansible.builtin.import_tasks: schema.yml

- name: Include argon2 tasks
  ansible.builtin.import_tasks: argon2.yml

- name: Include tls tasks
  ansible.builtin.import_tasks: tls.yml
  when: slapd_enable_tls

- name: Set the cn=config database root credentials
  community.general.ldap_attrs:
    dn: olcDatabase={0}config,cn=config
    attributes:
      olcRootPW: "{{ slapd_config_passwd }}"
    state: exact

- name: Require authn to get ldap access
  community.general.ldap_attrs:
    dn: olcDatabase={-1}frontend,cn=config
    attributes:
      olcRequires: authc
    state: exact

- name: Check if default database files exists
  ansible.builtin.stat:
    path: /var/lib/ldap/data.mdb
  register: slapd_default_data_mdb_stat

- name: Remove default database
  when: slapd_default_data_mdb_stat.stat.exists
  block:
    - name: Remove default database config
      community.general.ldap_entry:
        dn: olcDatabase={1}mdb,cn=config
        state: absent

    - name: Remove default database files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/ldap/data.mdb
        - /var/lib/ldap/lock.mdb
      notify: Restart slapd

- name: Databases provisioning
  ansible.builtin.include_tasks: database.yml
  loop: "{{ slapd_databases }}"
  loop_control:
    extended: true

- name: Deploy firewall rule
  ansible.builtin.copy:
    content: |
      tcp dport 636 accept \
      comment "Accept ldaps access"
    dest: /etc/nftables.d/filter-input-v6/slapd.nft
    mode: "0644"
  notify: Reload nftables
  when: slapd_enable_tls
