# SPDX-License-Identifier: MIT
---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Deploy nginx configuration
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload nginx

- name: Deploy tls snippet
  ansible.builtin.template:
    src: tls-params.conf.j2
    dest: /etc/nginx/snippets/tls-params.conf
    mode: "0644"
  notify: Reload nginx

- name: Disable default vhost
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy proxy vhosts
  ansible.builtin.template:
    src: "vhost-{{ item }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    mode: "0644"
  loop:
    - grafana
  notify: Reload nginx

- name: Enable proxy vhosts
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
  loop:
    - grafana
  notify: Restart nginx

- name: Deploy firewall rules
  ansible.builtin.copy:
    content: |
      tcp dport { 80, 443 } accept \
      comment "Accept http(s) access"
      udp dport 443 accept \
      comment "Accept HTTP/3 access"
    dest: /etc/nftables.d/filter-input-v6/nginx-proxy.nft
    mode: "0644"
  notify: Reload nftables
