# SPDX-License-Identifier: MIT
---
- name: Create wireguard chain drop-in directory
  ansible.builtin.file:
    path: /etc/nftables.d/filter-input-wg
    state: directory
    mode: "0755"

- name: Deploy firewall variables
  ansible.builtin.template:
    src: defines.nft.j2
    dest: /etc/nftables.d/defines/wireguard.nft
    mode: "0644"
  notify: Restart nftables

- name: Deploy firewall rules
  ansible.builtin.template:
    src: firewall.nft.j2
    dest: /etc/nftables.d/wireguard.nft
    mode: "0644"
  notify: Restart nftables

- name: Open port for the Wireguard
  ansible.builtin.copy:
    content: |
      udp dport $wg_port accept \
      comment "Traffic for internal vpn"
    dest: /etc/nftables.d/filter-input-v6/wireguard.nft
    mode: "0644"
  notify: Restart nftables
